#define LUA_LIB
#include "lua.h"
#include "lauxlib.h"

#include <windows.h>

static int lua_RegisterServiceCtrlHandler(lua_State *L)
{
    const char* svcname = luaL_checklstring(L, 1, NULL);
    int SvcCtrlHandler = luaL_ref(L, 2); // convert this to a c func
    SERVICE_STATUS_HANDLE h = RegisterServiceCtrlHandler(svcname, SvcCtrlHandler);
    if (h != 0)
    {
        lua_pushinteger(L, h);
        lua_pushnil(L);
    }
    else
    {
        lua_pushnil(L);
        lua_pushinteger(L, GetLastError());
    }
    return 2;
}

static const luaL_Reg winsvclib[] = {
        { "RegisterServiceCtrlHandler", lua_RegisterServiceCtrlHandler },
        { NULL, NULL }
};

#define SETLITERAL(v) (lua_pushliteral(L, #v), lua_pushliteral(L, v), lua_settable(L, -3))
#define SETINT(v) (lua_pushliteral(L, #v), lua_pushinteger(L, v), lua_settable(L, -3))

/*
** Open Windows service library
*/
LUALIB_API int luaopen_winsvc(lua_State *L) {
    luaL_register(L, "winsvc", winsvclib);

    // Some Windows Defines
    SETINT(ERROR);
    SETINT(NO_ERROR);

    // Service Defines
    SETLITERAL(SERVICES_ACTIVE_DATABASE);
    SETLITERAL(SERVICES_FAILED_DATABASE);
    SETINT(SC_GROUP_IDENTIFIER);

    SETINT(SERVICE_NO_CHANGE);

    SETINT(SERVICE_ACTIVE);
    SETINT(SERVICE_INACTIVE);
    SETINT(SERVICE_STATE_ALL);

    SETINT(SERVICE_CONTROL_STOP);
    SETINT(SERVICE_CONTROL_PAUSE);
    SETINT(SERVICE_CONTROL_CONTINUE);
    SETINT(SERVICE_CONTROL_INTERROGATE);
    SETINT(SERVICE_CONTROL_SHUTDOWN);
    SETINT(SERVICE_CONTROL_PARAMCHANGE);
    SETINT(SERVICE_CONTROL_NETBINDADD);
    SETINT(SERVICE_CONTROL_NETBINDREMOVE);
    SETINT(SERVICE_CONTROL_NETBINDENABLE);
    SETINT(SERVICE_CONTROL_NETBINDDISABLE);
    SETINT(SERVICE_CONTROL_DEVICEEVENT);
    SETINT(SERVICE_CONTROL_HARDWAREPROFILECHANGE);
    SETINT(SERVICE_CONTROL_POWEREVENT);
    SETINT(SERVICE_CONTROL_SESSIONCHANGE);
    SETINT(SERVICE_CONTROL_PRESHUTDOWN);
    SETINT(SERVICE_CONTROL_TIMECHANGE);
    SETINT(SERVICE_CONTROL_TRIGGEREVENT);

    SETINT(SERVICE_STOPPED);
    SETINT(SERVICE_START_PENDING);
    SETINT(SERVICE_STOP_PENDING);
    SETINT(SERVICE_RUNNING);
    SETINT(SERVICE_CONTINUE_PENDING);
    SETINT(SERVICE_PAUSE_PENDING);
    SETINT(SERVICE_PAUSED);

    SETINT(SERVICE_ACCEPT_STOP);
    SETINT(SERVICE_ACCEPT_PAUSE_CONTINUE);
    SETINT(SERVICE_ACCEPT_SHUTDOWN);
    SETINT(SERVICE_ACCEPT_PARAMCHANGE);
    SETINT(SERVICE_ACCEPT_NETBINDCHANGE);
    SETINT(SERVICE_ACCEPT_HARDWAREPROFILECHANGE);
    SETINT(SERVICE_ACCEPT_POWEREVENT);
    SETINT(SERVICE_ACCEPT_SESSIONCHANGE);
    SETINT(SERVICE_ACCEPT_PRESHUTDOWN);
    SETINT(SERVICE_ACCEPT_TIMECHANGE);
    SETINT(SERVICE_ACCEPT_TRIGGEREVENT);

    SETINT(SC_MANAGER_CONNECT);
    SETINT(SC_MANAGER_CREATE_SERVICE);
    SETINT(SC_MANAGER_ENUMERATE_SERVICE);
    SETINT(SC_MANAGER_LOCK);
    SETINT(SC_MANAGER_QUERY_LOCK_STATUS);
    SETINT(SC_MANAGER_MODIFY_BOOT_CONFIG);
    SETINT(SC_MANAGER_ALL_ACCESS);

    SETINT(SERVICE_QUERY_CONFIG);
    SETINT(SERVICE_CHANGE_CONFIG);
    SETINT(SERVICE_QUERY_STATUS);
    SETINT(SERVICE_ENUMERATE_DEPENDENTS);
    SETINT(SERVICE_START);
    SETINT(SERVICE_STOP);
    SETINT(SERVICE_PAUSE_CONTINUE);
    SETINT(SERVICE_INTERROGATE);
    SETINT(SERVICE_USER_DEFINED_CONTROL);
    SETINT(SERVICE_ALL_ACCESS);

    SETINT(SERVICE_RUNS_IN_SYSTEM_PROCESS);

    SETINT(SERVICE_CONFIG_DESCRIPTION);
    SETINT(SERVICE_CONFIG_FAILURE_ACTIONS);
    SETINT(SERVICE_CONFIG_DELAYED_AUTO_START_INFO);
    SETINT(SERVICE_CONFIG_FAILURE_ACTIONS_FLAG);
    SETINT(SERVICE_CONFIG_SERVICE_SID_INFO);
    SETINT(SERVICE_CONFIG_REQUIRED_PRIVILEGES_INFO);
    SETINT(SERVICE_CONFIG_PRESHUTDOWN_INFO);
    SETINT(SERVICE_CONFIG_TRIGGER_INFO);
    SETINT(SERVICE_CONFIG_PREFERRED_NODE);
    // reserved                                     10
    // reserved                                     11
    SETINT(SERVICE_CONFIG_LAUNCH_PROTECTED);

    SETINT(SERVICE_NOTIFY_STATUS_CHANGE_1);
    SETINT(SERVICE_NOTIFY_STATUS_CHANGE_2);
    SETINT(SERVICE_NOTIFY_STATUS_CHANGE);

    SETINT(SERVICE_NOTIFY_STOPPED);
    SETINT(SERVICE_NOTIFY_START_PENDING);
    SETINT(SERVICE_NOTIFY_STOP_PENDING);
    SETINT(SERVICE_NOTIFY_RUNNING);
    SETINT(SERVICE_NOTIFY_CONTINUE_PENDING);
    SETINT(SERVICE_NOTIFY_PAUSE_PENDING);
    SETINT(SERVICE_NOTIFY_PAUSED);
    SETINT(SERVICE_NOTIFY_CREATED);
    SETINT(SERVICE_NOTIFY_DELETED);
    SETINT(SERVICE_NOTIFY_DELETE_PENDING);

    SETINT(SERVICE_STOP_REASON_FLAG_MIN);
    SETINT(SERVICE_STOP_REASON_FLAG_UNPLANNED);
    SETINT(SERVICE_STOP_REASON_FLAG_CUSTOM);
    SETINT(SERVICE_STOP_REASON_FLAG_PLANNED);
    SETINT(SERVICE_STOP_REASON_FLAG_MAX);

    SETINT(SERVICE_STOP_REASON_MAJOR_MIN);
    SETINT(SERVICE_STOP_REASON_MAJOR_OTHER);
    SETINT(SERVICE_STOP_REASON_MAJOR_HARDWARE);
    SETINT(SERVICE_STOP_REASON_MAJOR_OPERATINGSYSTEM);
    SETINT(SERVICE_STOP_REASON_MAJOR_SOFTWARE);
    SETINT(SERVICE_STOP_REASON_MAJOR_APPLICATION);
    SETINT(SERVICE_STOP_REASON_MAJOR_NONE);
    SETINT(SERVICE_STOP_REASON_MAJOR_MAX);
    SETINT(SERVICE_STOP_REASON_MAJOR_MIN_CUSTOM);
    SETINT(SERVICE_STOP_REASON_MAJOR_MAX_CUSTOM);

    SETINT(SERVICE_STOP_REASON_MINOR_MIN);
    SETINT(SERVICE_STOP_REASON_MINOR_OTHER);
    SETINT(SERVICE_STOP_REASON_MINOR_MAINTENANCE);
    SETINT(SERVICE_STOP_REASON_MINOR_INSTALLATION);
    SETINT(SERVICE_STOP_REASON_MINOR_UPGRADE);
    SETINT(SERVICE_STOP_REASON_MINOR_RECONFIG);
    SETINT(SERVICE_STOP_REASON_MINOR_HUNG);
    SETINT(SERVICE_STOP_REASON_MINOR_UNSTABLE);
    SETINT(SERVICE_STOP_REASON_MINOR_DISK);
    SETINT(SERVICE_STOP_REASON_MINOR_NETWORKCARD);
    SETINT(SERVICE_STOP_REASON_MINOR_ENVIRONMENT);
    SETINT(SERVICE_STOP_REASON_MINOR_HARDWARE_DRIVER);
    SETINT(SERVICE_STOP_REASON_MINOR_OTHERDRIVER);
    SETINT(SERVICE_STOP_REASON_MINOR_SERVICEPACK);
    SETINT(SERVICE_STOP_REASON_MINOR_SOFTWARE_UPDATE);
    SETINT(SERVICE_STOP_REASON_MINOR_SECURITYFIX);
    SETINT(SERVICE_STOP_REASON_MINOR_SECURITY);
    SETINT(SERVICE_STOP_REASON_MINOR_NETWORK_CONNECTIVITY);
    SETINT(SERVICE_STOP_REASON_MINOR_WMI);
    SETINT(SERVICE_STOP_REASON_MINOR_SERVICEPACK_UNINSTALL);
    SETINT(SERVICE_STOP_REASON_MINOR_SOFTWARE_UPDATE_UNINSTALL);
    SETINT(SERVICE_STOP_REASON_MINOR_SECURITYFIX_UNINSTALL);
    SETINT(SERVICE_STOP_REASON_MINOR_MMC);
    SETINT(SERVICE_STOP_REASON_MINOR_NONE);
    SETINT(SERVICE_STOP_REASON_MINOR_MAX);
    SETINT(SERVICE_STOP_REASON_MINOR_MIN_CUSTOM);
    SETINT(SERVICE_STOP_REASON_MINOR_MAX_CUSTOM);

    SETINT(SERVICE_CONTROL_STATUS_REASON_INFO);

    SETINT(SERVICE_SID_TYPE_NONE);
    SETINT(SERVICE_SID_TYPE_UNRESTRICTED);
    SETINT(SERVICE_SID_TYPE_RESTRICTED);

    SETINT(SERVICE_TRIGGER_TYPE_DEVICE_INTERFACE_ARRIVAL);
    SETINT(SERVICE_TRIGGER_TYPE_IP_ADDRESS_AVAILABILITY);
    SETINT(SERVICE_TRIGGER_TYPE_DOMAIN_JOIN);
    SETINT(SERVICE_TRIGGER_TYPE_FIREWALL_PORT_EVENT);
    SETINT(SERVICE_TRIGGER_TYPE_GROUP_POLICY);
    SETINT(SERVICE_TRIGGER_TYPE_NETWORK_ENDPOINT);
    SETINT(SERVICE_TRIGGER_TYPE_CUSTOM_SYSTEM_STATE_CHANGE);
    SETINT(SERVICE_TRIGGER_TYPE_CUSTOM);

    SETINT(SERVICE_TRIGGER_DATA_TYPE_BINARY);
    SETINT(SERVICE_TRIGGER_DATA_TYPE_STRING);
    SETINT(SERVICE_TRIGGER_DATA_TYPE_LEVEL);
    SETINT(SERVICE_TRIGGER_DATA_TYPE_KEYWORD_ANY);
    SETINT(SERVICE_TRIGGER_DATA_TYPE_KEYWORD_ALL);

    SETINT(SERVICE_START_REASON_DEMAND);
    SETINT(SERVICE_START_REASON_AUTO);
    SETINT(SERVICE_START_REASON_TRIGGER);
    SETINT(SERVICE_START_REASON_RESTART_ON_FAILURE);
    SETINT(SERVICE_START_REASON_DELAYEDAUTO);

    SETINT(SERVICE_DYNAMIC_INFORMATION_LEVEL_START_REASON);

    SETINT(SERVICE_LAUNCH_PROTECTED_NONE);
    SETINT(SERVICE_LAUNCH_PROTECTED_WINDOWS);
    SETINT(SERVICE_LAUNCH_PROTECTED_WINDOWS_LIGHT);
    SETINT(SERVICE_LAUNCH_PROTECTED_ANTIMALWARE_LIGHT);

    return 1;
}
